service: flask-lambda-app

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 256
  timeout: 10
  stage: dev

functions:
  app:
    handler: lambda_handler.handler
    events:
      - httpApi: '*'  # automatically creates a scalable HTTP API Gateway

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
